trigger:
  branches:
    include: [ main ]

stages:
  - stage: BuildAndTest
    jobs:
      - template: pipelines/templates/build-test.yml
  - stage: Containerize
    dependsOn: BuildAndTest
    jobs:
      - template: pipelines/templates/containerize.yml
  - stage: DeployPOC
    dependsOn: Containerize
    jobs:
      - template: pipelines/templates/deploy.yml
  - stage: DAST
    dependsOn: DeployPOC
    jobs:
      - template: pipelines/templates/dast.yml
  - stage: Gate
    dependsOn: DAST
    jobs:
      - template: pipelines/templates/gate.yml
