[SERVICE]
    Flush 1
    Daemon Off
    Log_Level info

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[FILTER]
    Name modify
    Match *
    Rename log message
    Add cluster_name weather-sim-local
    Add observability_namespace docker-compose

[OUTPUT]
    Name kafka
    Match *
    Brokers kafka:29092
    Topics weather-sim.logs
    Format json
    Retry_Limit False
    rdkafka.request.required.acks 1
