apiVersion: v1
kind: Service
metadata:
  name: weather-sim-api
  {{- with .Values.service.apiAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.apiType }}
  selector: { app: weather-sim-api }
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiTargetPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: weather-sim-web
  {{- with .Values.service.webAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.webType }}
  selector: { app: weather-sim-web }
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webTargetPort }}
      protocol: TCP
