apiVersion: v1
kind: Service
metadata:
  name: weather-sim-api
spec:
  selector: { app: weather-sim-api }
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: weather-sim-web
spec:
  selector: { app: weather-sim-web }
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: 80
