apiVersion: v2
name: observability-stack
description: Umbrella Helm chart for the observability namespace stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: elasticsearch
    version: 0.1.0
    repository: file://../elasticsearch
    condition: elasticsearch.enabled
  - name: kibana
    version: 0.1.0
    repository: file://../kibana
    condition: kibana.enabled
  - name: kafka
    version: 0.1.0
    repository: file://../kafka
    condition: kafka.enabled
  - name: fluent-bit
    alias: fluentBit
    version: 0.1.0
    repository: file://../fluent-bit
    condition: fluentBit.enabled
  - name: logstash
    version: 0.1.0
    repository: file://../logstash
    condition: logstash.enabled
