input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["weather-sim.logs"]
    group_id => "weather-sim-logstash"
    codec => "json"
    auto_offset_reset => "earliest"
  }
}

filter {
  mutate {
    add_field => {
      "observability_namespace" => "docker-compose"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "weather-sim-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
