[SERVICE]
    Flush 1
    Daemon Off
    Log_Level info

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[FILTER]
    Name modify
    Match *
    Add platform weather-sim

[OUTPUT]
    Name cloudwatch_logs
    Match *
    region ${AWS_REGION}
    log_group_name ${CLOUDWATCH_LOG_GROUP}
    log_stream_prefix api-
    auto_create_group true
