apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.serviceName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: broker
      port: {{ .Values.service.port }}
      targetPort: broker
    - name: controller
      port: {{ .Values.service.controllerPort }}
      targetPort: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
