{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.uiName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "kafka.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
