apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
data:
  elasticsearch.yml: |-
{{- tpl (.Files.Get "elasticsearch.yml") . | nindent 4 }}
